version: "3.9"
services:
    nginx:
        build: ./nginx/
        container_name: monitoring-nginx
        working_dir: /home/monitoring
        ports:
            - 8081:80
        volumes:
            - ./src:/home/monitoring
    php:
        build: ./php/
        container_name: monitoring-php
        working_dir: /home/monitoring
        volumes: 
            - ./src:/home/monitoring
            - ./src/storage/logs/php-fpm:/var/log/php-fpm
        env_file:
            - ./.env
    db:
        container_name: monitoring-db
        image: mariadb:10.6.5
        env_file:
            - ./mysql/.env
        volumes:
            - ./mysql/data:/var/lib/mysql
        ports:
            - 3336:3306